name: Notify Slack on Git Commit

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Commit Details
      id: get_commit
      run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Send Slack Notification
      uses: act10ns/slack@v2
      with:
        channel: '#mar-2024-weekday-batch'
        text: "New commit on main branch: *${{ env.COMMIT_MESSAGE }}*"
