name: Notify Slack on Git Commit

on:
  push:
    branches:  # Trigger on all branches
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Commit Details
      id: get_commit
      run: |
        echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
        echo "COMMIT_AUTHOR=$(git log -1 --pretty=%an)" >> $GITHUB_ENV

    - name: Send Slack Notification
      uses: act10ns/slack@v2
      with:
        webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
        channel: '#mar-2024-weekday-batch'
        status: success  # or failure if you're reporting a job status
        message: |
          New commit on branch `${{ github.ref_name }}`:
          - *commit*: ${{ env.COMMIT_MESSAGE }}
          - *by*: ${{ env.COMMIT_AUTHOR }}
